sudo: required

branches:
  only:
    - master

language: go

go:
- 1.10.x

env:
  global:
    - APP=kubebot
    - BUILD_ON_DEPLOY=true
    # DOCKER_USERNAME
    - secure: "TVe/V+pMy5YWQ3l2A4imAECkY+TMboZgy2rGc8VClH0EmS1PJwwsEnsOJUezGPYLCEBX4zonkN4Q+nA/LT2W3UVpPxLmG0kR0+0ffopviuqZ5CBRMvuXmj8MeyXeGHZ+BVKHRsk0SiVShXcRoJXMwKNONLXelwNdMDmdUALS/7PDdC/yQnrJJSFP7Mu+lEhzGaqtd9/lBbI0iBn+PP+cvVpKCw+2jzki3ZSG9TX6vaGbTTzw+A04+IIc2KK2GADA3KUDS1ixh+rQz77HzaOEHS973aLbmaTT221UjEehJYCEmjpym9h0DxN7YejO0fRjDGxl14diiC6Al9NOsqr56bao5831vh+50fx6qbYoLZnCvR5ejJdrJb+1/oW5wdjO7gcY31atV5usZXdbCtCHO2SpqubJyAd1xanBoTyF3+S1e76P+N2mdSlVt8hDwTA5xwRMaXWgF/8ZDdM3pHYomW+Rwlk4nA/x5Ar2xOaCmSO3Pgf8iQU+2NqVEooqd29ARJS5jI05+M8Cn6sg03stW46P0g4DajlGTPCoR06nERHboNtmTjHzSC2CWh3VMpTmxrO2s9IK/wKzRVdNpz17WZ4DXHtWC/4F3RfAmfA6aPPr75/I6ecXUOTi1qKXlD+jgqOe/Xt08S20ihtCJslI3XHHf+FHD+D5l4Qif6kTTug="
    # DOCKER_PASSWORD
    - secure: "Pj5btmZo+aiuAOAWUGD+q5VQyw27HV5fZZdB2omrjNsle+RRZm20o3EXDQ6qruKab5JBP78qpZcTTJjJcnqLmwH6KXKSTAU8QJb3FJdSGOPDdyTVKU6carKcATO7rFXve1x31tdclSYd64HDy18LQbfei3QQ5WzwLxK1AYeSX+dHlOR8fW6olJ5j4R0IETTQs9mKpYM1bABhNYRkmQ9eQaU4OYpH8Ap6QJSvzR+k5tlYs2P45UoSf59BgCEZjbxpgj/oG4VSr5Mw0/aiszpxbF78G160Q/UxqN1C6orR10nwqj+RvdUdNLvsogOQ5iasKTs8jR0jEswqAUX26eFPXb74BU92U7YedUwsT4xrYujm3HtNh8HesjEZdSbbEQ48+heLL0/9UP+3QNVGR7xlvP2Rt0txmIiEZR1XKQiYO+0xVxxh+yAuP2JY3ZqsAeYPyFr4aOtiIUZA7O/lW/WJmCp2mvedDUkXywgAbnutgpqmB4xw3O2/6+86sbRMfYGsYo/6qv8tI3N09DGDe3d4bwVaVqRljR3FpDd79ab/S9JSAo1Qz0/oDITvulCtYLQTwF14DM+1GTExKmFKXSGNXDCzxTNT8XxXje6XU007DOafTJfPSEy18bfrE8BQx73rrZ907kEHrmS3hcAGRCRrtSbZ4OMWX/9ERhE/csW394Q="
    # NAMESPACE
    - secure: "QGsX8Tm9NqT81Ke1FtLlGD5NFBiM050LdWznXLbc3JD15zdtG40+oT296b+YM1Dc2m3mLNuxAtVKxe7hwz0oGEqkhuOWf4Cta5NhsU0qG6+L7fwFQovgAhUIjFiRqCdYdzGuU/nw6wuH3gcOUESx9cKFIGaaUDn/bEguFWnvYPlZzqDd1+n9utqxLrULbA3h7jzrxu6BM92Dh12rQIP63awmkXSoGMB3hqxrjpFpO83ipVgH7pYgQNP6cXJPvQURqK2iLnrZm3T6dSInCTcLVuPF9zdE1W/Brs9hoI69t/bTrlOguB1yT+ItVVWizMjSTQvmYKu+11vhO1Mo9IivP+O2U01aO/gNfovlxPDTqKoLtb3SBG1F2J1DyX/zj4vCGGrnZIjM/ZmeNoEnyT3BJWdfVvLSUDN9eQq/WkizKVpnvUu/O5bp6owTpbPhJPeauGM5t4JpUaqBies3VKf1K/sWsmXTyPqeJULsdhC0xD99wWYv6IQDYIUq3TJmkr9+0AFJ7wWOKTpSruA4O6skhbGz+CcFCpe6iR8mIuSeu0XF5L6SMLkaQ/X6iCo9//A8LppeMrqOWhi0u5G+mYhaUkP1CMJ/PsBhJelpGj6Tm0+wbmHBG0sdw57d5MzkTGhKbrpPEQMczLVcr3hxsaxn05HLj5x6G/DHoTYrsdc6KyM="
    # KEY
    - secure: "F0OdNlAodpHXhoi/MsbqwdIXy3MmpKQncwz/MFov0g7Qj/lcWT9voqPgTZYkRqJEm9aoI3q1c4GuQxTVw3HWRzmMws2QvibrA62sHv3FnUAfJqpPLyJgdH81OJ9fvDH0EGeH7oy83Et5Vw/RJHGFdGxwlgmBgRi4d3ZpFEVc+4NE+wyJjhRwXw9n0/DElLTEuXG0TzwsPxeNalI9LKupgUwhR/Qo950wq3VSpLgDxVxlzRLzfzuFcZ6VqZHuxrFHxyNTCSbGP9m3pxgBkbPWFyvinPNCEsxYwk/X4tMLdNsVWhQbg0YnoMKUxKwYB7aJlqmjiet/ms9UDaKm2qRkhXbEHfyMN7t99nyzdSmmulOlafa+caq9Y/Y5ZJEo+jE5tR2bKiDuIAlmKvR53TG1gGM9LtJCcN7VYmkGgBO/PQSux7lEFMBI7rmpcCI50pLAAvx0mrHNzOj/rl8Xv5Q5eAlekIMp3o04FGVCQM/tIahLt1TnTVQc9hDclYpyugYCL3Jd4HfP6hmnQlc4sD4T8KhI/rlwew9sNBmSroe0EzRtfMCWndRBfvTrwFy+XmqrIA4vCXjBu5m9CPDC9y+upfZkcQnmOymcu/Vtzx/eWf+qfS7o9zecR6bFUNJKqDc2sLXfE7J7CPMMOSEhF5rom7Q1bNg+OKheUPjRavr7P3k="
    # GITHUB
    - secure: "PofK71q/jfZgxlaxFmGidC4mLrqMInNe8YyCnonmYCDvwNOU4EK1HTt+x1xYdA6PH/VZ59+Nqceq3jM+z7iaZZVfcb822+sKrUTMUBc2FDDiRMmJ4w5M6K742q90FBaYbV1YEAQsGNk7qlXomwX7cwvvHUNz6rMAa3ycUOXHVpNdmE4dFTMfRGab/PuZE6EBmMxKqpKuj8f4RPz9lXdVbf7Z79wzt02jjE39xQFzpq2OicBoM9lZgdY//xZtq9WkkSjLAEjy1gcqoywlFD3i2n4B5a7GIZMubfoWKpGKYP4nJRiOkAXQh2D29E1wE6mc9kwo6K5c9t7Q/UnF68nCC2vZNawWtzKZcRe+VuAoivoVvtt+WcsjkjFDg/7wY8wcVM5b52uBf2NEP17BXc/r5zujkPzFllAAp1y6yUHYiSjtAHwWAqej6CmmyECErY+3fzgre2b9EZNPNAy1gMFA7LnWN7GjzEyDz6lZBTFIbTIByh76v+L6OD1ROKU4MrQr9lyjKXnmITDiRQ37QpkOYIkt8f5GjhxS3cnpVmjyCd9uM7ZVj0YmxHobkT0FE8+oYolGy+W+ZkmXPsSh6FRCdFIOl9x2QohAW8RCHhKI1KXTn7Imbjmn6LdVkOa/jGPF9sQmAq584T2u+tok/dKqdyH8nFa0j8gZ3f17pKhuLS8="

before_install:
- go get -u github.com/golang/dep/cmd/dep

install:
- dep ensure

script:
- go test ./...

deploy:
  provider: script
  script: ./deploy/deploy_wrapper.sh
  skip_cleanup: true
  on:
    branch: master
