apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    env: "{{ .Values.environment }}"
    tier: kubebot
  name: kubebot
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: kubebot
  template:
    metadata:
      labels:
        tier: kubebot
    spec:
      containers:
      - env:
        - name: KUBEBOT_SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: kubebot
        - name: KUBEBOT_SLACK_CHANNELS_IDS
          valueFrom:
            secretKeyRef:
              key: channel
              name: kubebot
        - name: KUBEBOT_SLACK_ADMINS_NICKNAMES
          value: horvathors phil.quinn frank tobias vladimir.indik iris
        - name: KUBEBOT_SLACK_VALID_COMMANDS
          value: get describe logs scale clusterinfo version
        image: "{{ .Values.imageTag }}"
        imagePullPolicy: Always
        name: kubebot
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
      - name: "gesundheitscloud-regsecret"
